#include "test_utils.h"
#include "sfall.h"

procedure start begin
    display_msg("Testing iface_tag functions...");
    // assumes no iface tags active in the save game

    // SNEAK
    show_iface_tag(0);
    call assertTrue("show_iface_tag(SNEAK)", is_iface_tag_active(0));
    hide_iface_tag(0);
    call assertFalse("hide_iface_tag(SNEAK)", is_iface_tag_active(0));

    // LEVEL
    show_iface_tag(3);
    call assertTrue("show_iface_tag(LEVEL)", is_iface_tag_active(3));
    hide_iface_tag(3);
    call assertFalse("hide_iface_tag(LEVEL)", is_iface_tag_active(3));

    // ADDICTED
    show_iface_tag(4);
    call assertTrue("show_iface_tag(ADDICTED)", is_iface_tag_active(4));
    hide_iface_tag(4);
    call assertFalse("hide_iface_tag(ADDICTED)", is_iface_tag_active(4));

    // POISONED
    call assertFalse("hide_iface_tag(POISONED)", is_iface_tag_active(1));

    // RADIATED
    call assertFalse("hide_iface_tag(RADIATED)", is_iface_tag_active(2));

    call report_test_results("iface_tag");
end
